### ISSUE TITLE
Migration of service from Data Power to Apigee

### ISSUE THREAD

**Issue by AshwithGundu** [DinoChiesa/ApigeeEdge-Java-WsSec-Signature-2#1]
Hi Dino,

Please find the following updates required in JavaCallout.

![3](https://user-images.githubusercontent.com/31713102/66948821-0890c780-f01b-11e9-888b-438d7a7f654b.PNG)

Regards,
Ashwith

**Comment by DinoChiesa** [comment]
Hoi Ashwith, I know this is a really old message of yours. 
And
The differences you side are mostly non-issues.
The value of the XML prefix string has no semantic meaning in XML, therefore the difference between wsse and wssec is immaterial. 
The placement of the XML namespace declarations, similarly does not matter. 
One difference that is important is the wsu:Id on the Body of the message.  Apigee is applying that Id for the purposes of signing the Body.  If that Id attribute is missing from the element, then the element cannot be signed (or more correctly, the signature cannot refer to the signed element). Since it is missing in the Datapower version of your message, that means Datapower is not signing the Body.  That is somewhat surprising to me. Without a signature, the Body element can be modified to be -anything-.  There is no message integrity guarantee. So this perhaps is a problem with your Datapower configuration.  You may want to Check that.

**Comment by DinoChiesa** [comment]
Not an issue
